### ISSUE TITLE
Add a command to focus the pane by specifying the direction

### ISSUE THREAD

**Issue by amaany3** [zed-industries/feedback#476]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

It is not intuitive to use separate focus commands (file tree, git integration) to focus the editor, sidebar, and footer panels.

### Describe the solution you'd like

Add a command to focus the pane by specifying the direction.
It would be intuitive and easy to use if it were possible to focus on a pane by specifying a direction, like tmux.
Atom provided that functionality with the following command.

```yml
'.platform-darwin atom-workspace':
  'ctrl-h': 'window:focus-pane-on-left'
  'ctrl-l': 'window:focus-pane-on-right'
  'ctrl-j': 'window:focus-pane-below'
  'ctrl-k': 'window:focus-pane-above'
```
